# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release

on:
  push:
    branches: [ master ]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: use node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Create Release Pull Request
      uses: changesets/action@v1
      with:
          version: pnpm run version     # 自定义版本命令
          # commit: 'chore: update versions'  # 提交信息
          # title: 'chore: update versions'   # PR 标题
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
